### ISSUE TITLE
Fatal error: Cannot access protected property ThumbnailImage::$height in ..S5SlideShow.php on line 138

### ISSUE THREAD

**Issue by tosher** [mediawiki4intranet/S5SlideShow#2]
Mediawiki 1.25.1

``` php
# $thumb->height = ceil( $thumb->height * $hp['width'] / $thumb->width );
# $thumb->width = $hp['width'];
$params = array(
    'alt' => $fp['alt'],
    'title' => $fp['title'],
    # add new lines
    'override-height' => ceil( $thumb->getHeight() * $hp['width'] / $thumb->getWidth() ),
    'override-width' => $hp['width'],
);
```

**Comment by vitalif** [comment]
What's the minimum MW version that supports 'override-height' and 'override-width'?

**Comment by tosher** [comment]
Protected properties:
https://github.com/wikimedia/mediawiki/commit/ea7c809ec72c09049d7e5c641b5b23b0de3dab8f
Overrides:
https://github.com/wikimedia/mediawiki/commit/14b3f8767bdcfe7f5d346f4b4b3e55cc2d32044a

**Comment by vitalif** [comment]
Thanks for reporting the fix and sorry for long waiting, try out the master branch and report if there still are problems :)
